<?php

/**
 * @file
 * Module hook implements.
 */

use \Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter.
 * Checks for a project crew field and adds group id to its selection view arguments.
 */
function people_group_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  if (isset($form['field_prj_crew'])) {
    $group_id = \Drupal::routeMatch()->getRawParameter('group');
    $form['field_prj_crew']['widget'][0]['target_id']['#selection_settings']['view']['arguments'] = [$group_id];
  }

}