version: '2'

volumes:
  nextcloud:
  db:

services:

  db:
    container_name: tmi_cloud_db
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./local/db/data:/var/lib/mysql
      - ./local/db/log:/var/log
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    restart: always

  app:
    container_name: tmi_cloud_app
    image: nextcloud:stable-apache
    ports:
      - 41000:80
    links:
      - db
    volumes:
      - ./local/app/html:/var/www/html
      - ./local/app/log:/var/log
    environment:
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
    restart: always

