version: '2'

services:

  cloud_db:
    container_name: tmi_cloud_db
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    networks:
      - proxy_tmi
    volumes:
      - ./local/db/data:/var/lib/mysql
      - ./local/db/log:/var/log
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    restart: always

  cloud_app:
    container_name: tmi_cloud_app
    image: nextcloud:stable-apache
    networks:
      - proxy_tmi
    ports:
      - 41000:80
    links:
      - cloud_db
    volumes:
      - ./local/app/html:/var/www/html
      - ./local/app/log:/var/log
    environment:
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=cloud_db
    restart: always
