version: '2'

# Copy default.env to environment.env and change passwords.

services:

  app:
    container_name: tmi_cloud
    image: nextcloud:18.0
    networks:
      - nextcloud_network
    depends_on:
      - db
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./local/proxy/certs:/etc/nginx/certs:ro
      - ./local/nextcloud/config:/var/www/html/config
      - ./local/nextcloud/custom_apps:/var/www/html/custom_apps
      - ./local/nextcloud/data:/var/www/html/data
      - ./local/nextcloud/themes:/var/www/html/themes
    env_file: environment.env
    restart: unless-stopped

  collab:
    container_name: tmi_cloud_collab
    image: collabora/code
    networks:
      - nextcloud_network
    depends_on:
      - proxy
    cap_add:
      - MKNOD
    ports:
      - 9980:9980
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./local/proxy/certs:/etc/nginx/certs:ro
    env_file: environment.env
    restart: unless-stopped

  db:
    container_name: tmi_cloud_data
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./local/data:/var/lib/mysql
    env_file: environment.env
    restart: unless-stopped

  proxy:
    container_name: tmi_cloud_proxy
    image: jwilder/nginx-proxy:alpine
    networks:
      - nextcloud_network
    ports:
      - 41000:80
      - 41010:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./local/proxy/certs:/etc/nginx/certs:ro
      - ./local/proxy/conf.d:/etc/nginx/conf.d:rw
      - ./local/proxy/vhost.d:/etc/nginx/vhost.d:rw
      - ./local/proxy/html:/usr/share/nginx/html:rw
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped

networks:
  nextcloud_network: