version: '3'

services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - ./local/data/base:/var/lib/postgresql/data
    env_file:
      - db.env

  pgbackups:
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
      - ./local/data/backups:/backups
    links:
      - db
    depends_on:
      - db
    env_file:
      - db.env

  app:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - ./local/nextcloud:/var/www/html
    env_file:
      - db.env
    depends_on:
      - db

  web:
    build: ./local/images/web
    restart: always
    volumes:
      - ./local/nextcloud:/var/www/html:ro
    environment:
      - VIRTUAL_HOST=cloud.tmi.mobi
      - LETSENCRYPT_HOST=cloud.tmi.mobi
      - LETSENCRYPT_EMAIL=cia@afrikaburn.org
    depends_on:
      - app
    networks:
      - proxy-tier
      - default

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - ./local/certs:/etc/nginx/certs:ro
      - ./local/proxy/vhost.d:/etc/nginx/vhost.d
      - ./local/proxy/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - ./local/certs:/etc/nginx/certs
      - ./local/proxy/vhost.d:/etc/nginx/vhost.d
      - ./local/proxy/html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy

  collabora:
    image: collabora/code
    container_name: collabora
    restart: always
    expose:
      - 9980
    cap_add:
      - MKNOD
    environment:
      - domain=collabora.cloud.tmi.mobi
      - VIRTUAL_HOST=collabora.cloud.tmi.mobi
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=9980
      - VIRTUAL_PROTO=https
      - LETSENCRYPT_HOST=collabora.cloud.tmi.mobi
      - LETSENCRYPT_EMAIL=cia@afrikaburn.org
    networks:
      - proxy-tier

  image-export:
    image: jgraph/export-server
    container_name: nextcloud-drawio-export
    expose:
      - "8000"
    networks:
      - proxy-tier
    volumes:
      - ./local/fonts:/usr/share/fonts/drawio
    restart: always

  drawio:
    image: jgraph/drawio
    container_name: nextcloud-drawio
    expose:
      - 8080
    networks:
      - proxy-tier
    depends_on:
      - image-export
    environment:
      - VIRTUAL_HOST=drawio.cloud.tmi.mobi
      - VIRTUAL_PORT=8080
      - VIRTUAL_NETWORK=nginx-proxy
      - LETSENCRYPT_HOST=drawio.cloud.tmi.mobi
      - LETSENCRYPT_EMAIL=cia@afrikaburn.org
      - EXPORT_URL=http://image-export:8000/
    restart: always

networks:
  proxy-tier:
