<?php

/**
 * @file
 * Enables modules and site configuration for a tmi site installation.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter() for install_configure_form().
 *
 * Allows the profile to alter the site configuration form.
 */
function people_profile_form_alter(&$form, FormStateInterface $form_state) {
}

function people_profile_user_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display, $view_mode){
  // dpm($build);
}