# Schema for the configuration files of the OpenID Connect module.

openid_connect.settings:
  type: config_object
  label: 'OpenID Connect settings'
  mapping:
    always_save_userinfo:
      type: boolean
      label: 'Save user claims on every login'
    userinfo_mappings:
      type: mapping
      label: 'OpenID Connect settings'
      mapping:
        timezone:
          type: string
          label: 'Timezone'
        picture:
          type: string
          label: 'Picture'

openid_connect.settings.generic:
  type: config_object
  label: 'OpenID Connect Generic settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enable client'
    settings:
      type: mapping
      mapping:
        client_id:
          type: string
          label: 'Client ID'
        client_secret:
          type: string
          label: 'Client secret'
        authorization_endpoint:
          type: string
          label: 'Authorization endpoint'
        token_endpoint:
          type: string
          label: 'Token endpoint'
        userinfo_endpoint:
          type: string
          label: 'Userinfo endpoint'

openid_connect.settings.google:
  type: config_object
  label: 'OpenID Connect Google settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enable client'
    settings:
      type: mapping
      mapping:
        client_id:
          type: string
          label: 'Client ID'
        client_secret:
          type: string
          label: 'Client secret'
