version: '2'

services:

  proxy:
    container_name: tmi_proxy
    image: nginx:1.18.0-alpine
    ports:
    - 80:80
    - 443:443
    environment:
      - NGINX_HOST=tmi.mobi
      - NGINX_PORT=80
    volumes:
      - ./src/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./src/nginx/access.token.conf:/etc/nginx/access.token.conf:ro
      - ./src/nginx/cloud.conf:/etc/nginx/cloud.conf:ro
    networks:
      - tmi

networks:
  tmi:
    driver: bridge