version: '2'

services:
  web:
    container_name: tmi_proxy
    image: nginx:1.18.0-alpine
    ports:
    - 80:80
    - 443:443
    environment:
      - NGINX_HOST=tmi.mobi
      - NGINX_PORT=80
    volumes:
      - ./src/nginx.conf:/etc/nginx/nginx.conf:ro
