<?php

/**
 * @file
 * Module hook implements.
 */

use \Drupal\user\UserInterface;
use \Drupal\Core\Entity\EntityInterface;
use \Drupal\Core\Form\FormStateInterface;
use \Drupal\entity\Plugin\Core\Entity\EntityDisplay;

/**
 * Implements hook_form_FORM_ID_alter().
 * Hooked to display participant agreements on edit form.
 */
function project_core_form_node_project_form_alter(&$form, \FormStateInterface $form_state, $form_id) {
  dpm($form);
}
